### ISSUE TITLE
connection.notification not working

### ISSUE THREAD

**Issue by Fjuxx** [PaulAvery/node-xbmc-ws#3]
Hi, 

First off, the code looks very nice and tidy!

But the following is not working:
connection.notification('Player.OnPause', function() {
    console.log('Paused');
});

As Notification is not a function for connection.
i checked, and connection is only adding the methods and notifications from the schema as functions. But it never add's this general notification listener!

**Comment by PaulAvery** [comment]
Welp, apparently I am an idiot who does not even run his own code examples ^^
Should be fixed now.
