### ISSUE TITLE
Unhandeld error Connection timeout?

### ISSUE THREAD

**Issue by Fjuxx** [PaulAvery/node-xbmc-ws#4]
i'm getting this error if the target is not online: 

Unhandled rejection Error: connect ETIMEDOUT
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:983:19)

i looked, but i could not find where this error is coming from.
is this something the client needs to handle? (only thing i'm doing is reconnecting every 60 sec.)

it looks to be coming from the websocket library. but i have no idea where the rejection should be caught.

**Comment by PaulAvery** [comment]
Hmm.
Could you provide an example of how you try to establish a connection?
Usually any connection errors should result in rejection of the promise:

```js
var kodiws = require('xbmc-ws');
var kodi = kodiws('127.0.0.1', 9090);

kodi.catch(function(err) {
  console.error(err.stack);
});
```

If this does not catch the exception, this is obviously a bug.
For some reason I can't seem to get an ETIMEDOUT exception. And anything else (EHOSTUNREACH, ENOTFOUND) seems to correctly reject the promise.

**Comment by Fjuxx** [comment]
Nevermind,

i actually catched it, but then put it to console instead of using my logger.
sorry for the trouble
